export const initialState = {
	activePalette: 0,
	paletteData: [
		{
			name: 'Default',
			colors: [
				'#dddddd',
				'#999999',
				'#ffffff',
				'#000000',
				'#0282fa',
				'#555555',
				'#99dddd',
				'#222222',
				'#ffaa00',
				'#000000',
			],
			addresses: {
				header: {
					bg: 0,
					logo: 7,
					menuItem: 7,
					menuItemOffset: 4,
					menuBtn: 2,
					menuBtnBg: 1,
					menuBtnOffset: 3,
					menuBtnBgOffset: 4,
				},
				main: {
					bg: 2,
					title: 7,
					subTitle: 7,
					text: 7,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
				items: {
					bg: 0,
					name: 3,
					text: 3,
					btn: 3,
					btnBg: 6,
					btnOffset: 3,
					btnBgOffset: 4,
				},
				footer: {
					bg: 0,
					titles: 5,
					text: 5,
					link: 3,
					linkOffset: 4,
					social: 3,
					socialOffset: 4,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
			},
		},
		{
			name: 'Default2',
			colors: [
				'#dddd00',
				'#990099',
				'#00ffff',
				'#000099',
				'#6200fa',
				'#005555',
				'#9900dd',
				'#228800',
				'#ff0000',
				'#000000',
			],
			addresses: {
				header: {
					bg: 0,
					logo: 7,
					menuItem: 7,
					menuItemOffset: 4,
					menuBtn: 2,
					menuBtnBg: 1,
					menuBtnOffset: 3,
					menuBtnBgOffset: 4,
				},
				main: {
					bg: 2,
					title: 7,
					subTitle: 7,
					text: 7,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
				items: {
					bg: 0,
					name: 3,
					text: 3,
					btn: 3,
					btnBg: 6,
					btnOffset: 3,
					btnBgOffset: 4,
				},
				footer: {
					bg: 0,
					titles: 5,
					text: 5,
					link: 3,
					linkOffset: 4,
					social: 3,
					socialOffset: 4,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
			},
		},
		{
			name: 'White',
			colors: [
				'#eeeeee',
				'#ffffff',
				'#dddddd',
				'#aaaaaa',
				'#bbbbbb',
				'#cccccc',
				'#eeeeee',
				'#999999',
				'#888888',
				'#000000',
			],
			addresses: {
				header: {
					bg: 0,
					logo: 7,
					menuItem: 7,
					menuItemOffset: 4,
					menuBtn: 2,
					menuBtnBg: 1,
					menuBtnOffset: 3,
					menuBtnBgOffset: 4,
				},
				main: {
					bg: 2,
					title: 7,
					subTitle: 7,
					text: 7,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
				items: {
					bg: 0,
					name: 3,
					text: 3,
					btn: 3,
					btnBg: 6,
					btnOffset: 3,
					btnBgOffset: 4,
				},
				footer: {
					bg: 0,
					titles: 5,
					text: 5,
					link: 3,
					linkOffset: 4,
					social: 3,
					socialOffset: 4,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
			},
		},
	],
};

export const paletteTemplate = {
	name: 'Your New Palette',
	colors: [
		'#dddddd',
		'#999999',
		'#ffffff',
		'#000000',
		'#0282fa',
		'#555555',
		'#99dddd',
		'#222222',
		'#ffaa00',
		'#000000',
	],
	addresses: {
		header: {
			bg: 0,
			logo: 7,
			menuItem: 7,
			menuItemOffset: 4,
			menuBtn: 2,
			menuBtnBg: 1,
			menuBtnOffset: 3,
			menuBtnBgOffset: 4,
		},
		main: {
			bg: 2,
			title: 7,
			subTitle: 7,
			text: 7,
			btn: 2,
			btnBg: 3,
			btnOffset: 7,
			btnBgOffset: 2,
			btnBorder: 7,
		},
		items: {
			bg: 0,
			name: 3,
			text: 3,
			btn: 3,
			btnBg: 6,
			btnOffset: 3,
			btnBgOffset: 4,
		},
		footer: {
			bg: 0,
			titles: 5,
			text: 5,
			link: 3,
			linkOffset: 4,
			social: 3,
			socialOffset: 4,
			btn: 2,
			btnBg: 3,
			btnOffset: 7,
			btnBgOffset: 2,
			btnBorder: 7,
		},
	},
};
