export const initialState = {
	activePalette: 0,
	paletteData: [
		{
			name: 'Indie',
			colors: ['#994500', '#b2675e', '#c4a381', '#bbd686', '#eef1bd', '#009ffd', '#2a2a72', '#a882dd', '#b3f2dd', '#5171a5'],
			addresses: {
				header: {
					bg: 9,
					logo: 8,
					menuItem: 8,
					menuItemOffset: 6,
					menuBtn: 8,
					menuBtnBg: 6,
					menuBtnOffset: 6,
					menuBtnBgOffset: 4,
				},
				main: { bg: 3, title: 6, subTitle: 6, text: 6, btn: 8, btnBg: 6, btnOffset: 1, btnBgOffset: 3, btnBorder: 6 },
				items: { bg: 1, name: 4, text: 6, btn: 4, btnBg: 6, btnOffset: 1, btnBgOffset: 4 },
				footer: {
					bg: 4,
					titles: 5,
					text: 6,
					link: 6,
					linkOffset: 2,
					social: 6,
					socialOffset: 2,
					btn: 2,
					btnBg: 3,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
			},
		},
		{
			name: 'Minty',
			colors: ['#2c6e49', '#4c956c', '#fefee3', '#ffc9b9', '#d68c45', '#776871', '#802392', '#995fa3', '#9a98b5', '#88498f'],
			addresses: {
				header: {
					bg: 0,
					logo: 2,
					menuItem: 2,
					menuItemOffset: 4,
					menuBtn: 2,
					menuBtnBg: 1,
					menuBtnOffset: 2,
					menuBtnBgOffset: 4,
				},
				main: { bg: 2, title: 6, subTitle: 6, text: 6, btn: 2, btnBg: 6, btnOffset: 4, btnBgOffset: 2, btnBorder: 6 },
				items: { bg: 0, name: 2, text: 2, btn: 2, btnBg: 6, btnOffset: 2, btnBgOffset: 4 },
				footer: {
					bg: 0,
					titles: 4,
					text: 8,
					link: 2,
					linkOffset: 4,
					social: 2,
					socialOffset: 4,
					btn: 2,
					btnBg: 6,
					btnOffset: 4,
					btnBgOffset: 2,
					btnBorder: 6,
				},
			},
		},
		{
			name: 'Shades of Grey',
			colors: ['#eeeeee', '#ffffff', '#dddddd', '#aaaaaa', '#bbbbbb', '#cccccc', '#eeeeee', '#999999', '#888888', '#000000'],
			addresses: {
				header: {
					bg: 4,
					logo: 9,
					menuItem: 9,
					menuItemOffset: 2,
					menuBtn: 1,
					menuBtnBg: 9,
					menuBtnOffset: 8,
					menuBtnBgOffset: 0,
				},
				main: { bg: 2, title: 9, subTitle: 9, text: 9, btn: 9, btnBg: 1, btnOffset: 1, btnBgOffset: 7, btnBorder: 0 },
				items: { bg: 8, name: 1, text: 5, btn: 0, btnBg: 9, btnOffset: 0, btnBgOffset: 8 },
				footer: {
					bg: 4,
					titles: 9,
					text: 6,
					link: 9,
					linkOffset: 1,
					social: 9,
					socialOffset: 1,
					btn: 9,
					btnBg: 1,
					btnOffset: 1,
					btnBgOffset: 8,
					btnBorder: 0,
				},
			},
		},
		{
			name: 'Spooktober',
			colors: ['#b5c2b7', '#8c93a8', '#62466b', '#45364b', '#2d2327', '#ff220c', '#d33e43', '#fa8334', '#fc9e4f', '#ff521b'],
			addresses: {
				header: {
					bg: 4,
					logo: 7,
					menuItem: 7,
					menuItemOffset: 5,
					menuBtn: 4,
					menuBtnBg: 5,
					menuBtnOffset: 3,
					menuBtnBgOffset: 8,
				},
				main: { bg: 2, title: 7, subTitle: 7, text: 7, btn: 2, btnBg: 7, btnOffset: 7, btnBgOffset: 2, btnBorder: 7 },
				items: { bg: 3, name: 6, text: 7, btn: 2, btnBg: 7, btnOffset: 7, btnBgOffset: 2 },
				footer: {
					bg: 3,
					titles: 1,
					text: 0,
					link: 7,
					linkOffset: 5,
					social: 7,
					socialOffset: 5,
					btn: 2,
					btnBg: 7,
					btnOffset: 7,
					btnBgOffset: 2,
					btnBorder: 7,
				},
			},
		},
	],
}

export const paletteTemplate = {
	name: 'Your New Palette',
	colors: ['#dddddd', '#999999', '#ffffff', '#000000', '#0282fa', '#555555', '#99dddd', '#222222', '#ffaa00', '#000000'],
	addresses: {
		header: {
			bg: 0,
			logo: 7,
			menuItem: 7,
			menuItemOffset: 4,
			menuBtn: 2,
			menuBtnBg: 1,
			menuBtnOffset: 3,
			menuBtnBgOffset: 4,
		},
		main: {
			bg: 2,
			title: 7,
			subTitle: 7,
			text: 7,
			btn: 2,
			btnBg: 3,
			btnOffset: 7,
			btnBgOffset: 2,
			btnBorder: 7,
		},
		items: {
			bg: 0,
			name: 3,
			text: 3,
			btn: 3,
			btnBg: 6,
			btnOffset: 3,
			btnBgOffset: 4,
		},
		footer: {
			bg: 0,
			titles: 5,
			text: 5,
			link: 3,
			linkOffset: 4,
			social: 3,
			socialOffset: 4,
			btn: 2,
			btnBg: 3,
			btnOffset: 7,
			btnBgOffset: 2,
			btnBorder: 7,
		},
	},
}
